# 附魔台相关设置
enchanting-table:
  # 应该对IA的物品使用哪种附魔调节值？
  # 默认将IA物品作为钻石盔甲计算。
  # 详见Minecraft附魔机制：https://mc.163.com/20191010/31527_839270.html
  # 可能的值：WOOD, LEATHER, STONE, CHAIN, IRON, GOLD, DIAMOND, TURTLE, NETHERITE, OTHER
  enchantability: DIAMOND

  # 允许的附魔，默认遵守Minecraft原版机制。
  # 请从以下网站获取正确的附魔名称：
  # https://bukkit.windit.net/javadoc/org/bukkit/enchantments/Enchantment.html
  possible-enchantments:
    - WATER_WORKER
    - PROTECTION_EXPLOSIONS
    - PROTECTION_FIRE
    - PROTECTION_PROJECTILE
    - PROTECTION_ENVIRONMENTAL
    - OXYGEN
    - DURABILITY

# 铁砧相关设置
anvil:
  # 允许的附魔，默认遵守Minecraft原版机制。
  # 请从以下网站获取正确的附魔名称：
  # https://bukkit.windit.net/javadoc/org/bukkit/enchantments/Enchantment.html
  possible-enchantments:
    - WATER_WORKER
    - PROTECTION_EXPLOSIONS
    - PROTECTION_FIRE
    - PROTECTION_PROJECTILE
    - PROTECTION_ENVIRONMENTAL
    - OXYGEN
    - DURABILITY
    - BINDING_CURSE
    - VANISHING_CURSE
    - MENDING
    - THORNS

